### ISSUE TITLE
QUESTION: Use with Visual Studio Code possible?

### ISSUE THREAD

**Issue by FilBot3** [owenthereal/upterm#87]
# The Question

I am an avid terminal user, Neovim, tmux, and all the like so Upterm is amazing for me. However, some of my co-workers and friends do not live inside the terminal and use GUI IDE's such as Visual Studio Code. Is there a way use VSCode's `Remote Development -SSH` extension to connect to Upterm's SSH Server and be able to view with me as I work? 

## Current Error Output

<details>

```plaintext
[12:54:26.383] Log Level: 2
[12:54:26.386] remote-ssh@0.65.8
[12:54:26.386] linux x64
[12:54:26.387] SSH Resolver called for "ssh-remote+uptermd.upterm.dev", attempt 1
[12:54:26.388] "remote.SSH.useLocalServer": true
[12:54:26.388] "remote.SSH.path": undefined
[12:54:26.388] "remote.SSH.configFile": undefined
[12:54:26.388] "remote.SSH.useFlock": true
[12:54:26.389] "remote.SSH.lockfilesInTmp": false
[12:54:26.389] "remote.SSH.localServerDownload": auto
[12:54:26.389] "remote.SSH.remoteServerListenOnSocket": false
[12:54:26.389] "remote.SSH.showLoginTerminal": false
[12:54:26.389] "remote.SSH.defaultExtensions": []
[12:54:26.390] "remote.SSH.loglevel": 2
[12:54:26.390] SSH Resolver called for host: uptermd.upterm.dev
[12:54:26.390] Setting up SSH remote "uptermd.upterm.dev"
[12:54:26.395] Acquiring local install lock: /tmp/vscode-remote-ssh-48a5ecb6-install.lock
[12:54:26.430] Looking for existing server data file at /var/home/dudleyp/.var/app/com.visualstudio.code/config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-48a5ecb6-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.8/data.json
[12:54:26.431] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[12:54:26.439] Install and start server if needed
[12:54:26.476] PATH: /app/bin:/usr/bin:/app/tools/podman/bin:/usr/lib/sdk/golang/bin:/var/home/dudleyp/.var/app/com.visualstudio.code/data/node_modules/bin
[12:54:26.476] Checking ssh with "ssh -V"
[12:54:26.485] > OpenSSH_8.6p1, OpenSSL 1.1.1k  25 Mar 2021

[12:54:26.490] askpass server listening on /run/user/1000/vscode-ssh-askpass-59f8107e5f8a89dfd1a5728c561edb170e91f293.sock
[12:54:26.490] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-a68ca513540bb777882508442662771abd6fea3c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42591","-o","ConnectTimeout=15","uptermd.upterm.dev"],"dataFilePath":"/var/home/dudleyp/.var/app/com.visualstudio.code/config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-48a5ecb6-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.8/data.json"}
[12:54:26.490] Local server env: {"DISPLAY":":99.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/app/extra/vscode/code","VSCODE_SSH_ASKPASS_MAIN":"/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-59f8107e5f8a89dfd1a5728c561edb170e91f293.sock"}
[12:54:26.497] Spawned 315
[12:54:26.641] > local-server-1> Spawned ssh, pid=323
[12:54:26.643] stderr> OpenSSH_8.6p1, OpenSSL 1.1.1k  25 Mar 2021
[12:54:26.971] stderr> Connection closed by 157.230.199.75 port 22
[12:54:26.974] > local-server-1> ssh child died, shutting down
[12:54:26.980] Local server exit: 0
[12:54:26.980] Received install output: local-server-1> Spawned ssh, pid=323
OpenSSH_8.6p1, OpenSSL 1.1.1k  25 Mar 2021
Connection closed by 157.230.199.75 port 22
local-server-1> ssh child died, shutting down

[12:54:26.982] Failed to parse remote port from server output
[12:54:26.983] Resolver error: Error: 
	at Function.Create (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:397041)
	at Object.t.handleInstallOutput (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:395684)
	at Object.e [as tryInstallWithLocalServer] (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:435292)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:452665
	at async Object.t.withShowDetailsEvent (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:456460)
	at async /var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433816
	at async C (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433431)
	at async Object.t.resolve (/var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:454065)
	at async /var/home/dudleyp/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:526942
[12:54:26.990] ------
```

</details>

I do know that there is already a "co-editing" experience called Live Share for Visual Studio and VSCode, but I was having issues with it reverting changes we had made, and syncing improperly.

**Comment by owenthereal** [comment]
From https://code.visualstudio.com/docs/remote/ssh, my understanding is that a vscode client establishes an ssh tunnel to a remote server that runs the vscode server which allows editing files in the vscode client via the tunnel. Upterm does not speak the vscode remote ssh protocol, that's why you saw an error. We might be able to get Upterm to speak the same vscode remote ssh protocol but after a quick search, I could not find any reference of the spec or open-sourced code. Until then, this is not possible at the moment.

**Comment by FilBot3** [comment]
Thank you for looking @owenthereal . I'm comfortable with using Neovim/Vim so my pair-programmer can just watch while I do the things in there.
